baseurl = "/"
languageCode = "en-us"
title = "R Nahum"
theme = "hugo-theme-tokiwa"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

author = "Rnahumaf"
DefaultContentLanguage = "en"
hasCJKLanguage=true
enableInlineShortcodes = true
enableEmoji = true

[permalinks]
    post = "/:year/:month/:day/:slug"
    


[menu]
# Shown in the side menu.
  [[menu.main]]
    name = "Posts"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "Categories"
    url = "/categories/"  
    weight = 2

[[menu.main]]
    name = "About"
    weight = 3
    identifier = "about"
    url = "/about/"

[params]
    description = "Sentado, sonhando."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "public/animals.png"

    [params.logo]
    url = "public/animals.png"
    width = 50
    height = 50
    alt = "Logo"
    
[taxonomies]
category = "categories"
tag = "tags"

[social]
instagram="https://www.instagram.com/mera_sanidade/"
twitter="http://twitter.com/rnahumaf/"
youtube="https://www.youtube.com/c/RodrigoNAlvarezF/"
github="http://github.com/rnahumaf/"
    
[markup.goldmark.renderer]
unsafe= true

