---
title: Eu
author: Rodrigo Nahum
date: '2020-06-27'
slug: eu
categories:
  - vida
tags:
  - decisoes
description: ''
---

# Decisões que importam

<br>
`Escrever` é uma manifestação de interação social. A interação não é apenas importante, é `essencial`. Existem várias formas de interagir, mas a escrita é uma das mais difíceis para mim.

<br>
Eu sou uma pessoa difícil em muitos aspectos e parte dessa minha essência está relacionada à minha *incessante* curiosidade. Minha *patológica* curiosidade.

<br>
Este blog surgiu como um espelho dessa minha personalidade. É uma plataforma diferente, inspiradora, que utiliza elementos de habilidades que desenvolvi com a linguagem `R` de programação, mais uma vez, fruto de outras e outras curiosidades.

<br>
Contudo, essa frenética busca por coisas diferentes me *incomoda*. Eu não gosto de pensar que estou *perdendo tempo*. Dessa forma, sempre procuro formas de agregar as minhas habilidades, por mais distintas que sejam, para que haja convergência em pelo menos alguns pontos.

<br>
É definitivamente mais fácil, agradável e `recompensante` trabalhar com esta plataforma. Eu me sinto incluído num ambiente em que meus esforços anteriores se mostram úteis, o que me `motiva` a continuar produzindo.

<br>
Espero que essa experiência também possa ser agradável a quem visitar esta página.