---
title: Relato ginecologia
author: Rodrigo Nahum
date: '2020-06-29'
slug: relato-ginecologia
categories:
  - relatos
tags:
  - coronavírus
description: ''
---

`Data` 29 de junho de 2020

Cheguei nos ambulatórios de ginecologia do CHS às 9h00 junto com Bernardo, Christiane e Daniel. O grupo anterior ainda estava lá: Ieside, Márcio, Leonardo e Vanessa. Os residentes eram Marcelo e Arthur. Quando chegamos, o professor A.V. estava orientando os alunos, numa sala fechada. Havia outro residente junto, mas não lembro o seu nome.

Quando a porta foi aberta, percebemos que o professor A.V. estava sem `máscara` e sem `jaleco`, em roupa habitual. Quando nossos colegas saíram daquela sala, conversaram conosco, dizendo que o prof. A.V. `espirrou` duas vezes, sem máscara, enquanto estavam todos naquela sala fechada.

Imediatamente, `tirei uma foto` para registrar o fato e enviei para a Profa. Carla e a Profa. Marta, para que tomassem ciência disso. Naquele momento eu estava apenas com uma máscara cirúrgica, que não tem tanto a função de proteger o usuário, mas sim as pessoas ao redor. Ela não me ofereceria qualquer benefício, caso o professor estivesse doente e espirrasse na minha frente num ambiente aglomerado e mal ventilado.

Corri para o carro para colocar uma máscara `N95` valvulada, que eu recebera da faculdade na semana anterior, e deixei a máscara cirúrgica por cima, para proteger meus colegas (uma vez que as válvulas deixam escapar o ar exalado).

Voltei mais seguro para os ambulatórios, e percebi que a primeira turma já havia ido embora e o professor agora reunira a minha turma para conversar, na mesma sala. Dessa vez, a porta estava aberta, então eu pude manter distância enquanto ouvia ele falando sobre temas de gestão pessoal, como evitar ser `manipulado` e entender a manipulação das informações do `COVID-19`.

Felizmente, o professor foi embora em sequência, deixando que os residentes prosseguissem com as atividades. Os residentes todos usavam máscaras e mantinham as portas abertas, para ventilação, o que nos ajudou a nos tranquilizar.

A Profa. Marta me respondeu por Whatsapp que já havia encaminhado a denúncia para a coordenação do curso, que iria conversar com o professor. A Profa. Carla também me informou que escreveu no grupo dos professores a respeito do cumprimento das normas sanitárias, e reiterou que deveríamos atender aos ambulatórios de `2 em 2`. Se estivéssemos em número maior, poderiam sair 2, por exemplo.

O grupo que terminou o estágio de ginecologia e hoje entrou na obstetrícia nos disse que os professores da ginecologia são assim mesmo, a maioria não `acredita` no coronavírus e não usam `máscara`.

A partir de hoje procurarei participar das atividades com `faceshield` e N95.