---
title: O princípio da autossuficiência
author: Rodrigo Nahum
date: '2020-06-27'
slug: autossuficiente
categories:
  - vida
tags:
  - reflexões
description: ''
---

|  Autossuficiência  |  Resultado   |
|--------------------|--------------|
| Múltiplas habilidades | Trabalho sem ajuda |
| Facilidades  |  Inveja alheia  |
| Eficiência   |  Arrogância repulsiva  |

Quando somos `suficientes`, somos `rejeitados`. Essa reiejção não necessariamente é *injusta*, uma vez que, por um aspecto, as consequências dessa suficiência são *desejadas*.

Assim como a `carência` é manifestada por quem deseja `afeto`, a suficiência é manifestada por quem deseja o `afastamento`.

Qual é a vantagem da suficiência? Ora, se eu não preciso da sua ajuda, definitivamente a minha vantagem *não é* ter você por perto, mas algo diferente. Então o que é?

Assim como é verdade que seres sociais precisam de afeto, de proximidade humana e de visibilidade, também é verdade que, de alguma forma, seres sociais precisam de, pelo menos um pouco, do *contrário* de tudo isso.

Mas seriam todas as pessoas *capazes* de autossuficiência? Aqui eu postulo que nem todos são *capazes*, mas todos têm a *necessidade* da autossuficiência.

São nos momentos de autossuficiência que notamos as nossas `falhas` e os nossos verdadeiros `desejos`. Portanto a autossuficiência não é somente uma habilidade, mas um **treino** de autoconhecimento.

## Falhas do autoconhecimento

<br>
Quem pensa somente em `agradar` não conhece as próprias `limitações`. Agradar o próximo é um exercício de `interdependência`. Quem agrada não quer o bem, quer `agrado`. O exercício do agrado têm função nos relacionamentos íntimos, como entre famílias, amigos, cônjujes... e animais de estimação :smile:. 

<br>
Contudo, o agrado *sozinho* não implica em outras grandes qualidades de um relacionamento interpessoal, como a *segurança*, a *previsibilidade* e a *responsabilidade*. Essas qualidades requerem que o relacionamento se corresponda a algum tipo de `finalidade`. 

<br>
Previsibilidade é saber que, *toda a vez* que chove, o humor fica depressivo e mau-humorado. Responsabilidade é saber que, mesmo mau-humorado, o marido vai *ajudar* a limpar a casa no dia da faxina. Segurança é saber que, mesmo se você disser algo errado, você *não será censurado*. 

<br>
Para `transmitir ao próximo` as finalidades de se relacionar com *você*, você precisa se *autoconhecer*, e a melhor forma de fazer isso é se libertando, *provisoriamente*, da sua `necessidade de se relacionar`.