---
title: Inveja
author: Rodrigo Nahum
date: '2020-06-28'
slug: inveja
categories:
  - vida
tags:
  - reflexões
description: ''
---

A `inveja` é filha da desigualdade, da injustiça e do preconceito. A inveja não se sente, se `interpreta`. Quem escancara a hipocrisia dos tratamentos diferenciados, por exemplo, pode ser interpretado como invejoso.

Quem diz *sentir* inveja, na verdade, sente *outro tipo* de inveja, aquela *cômica*, *divertida*, *descontraída*. Porque a **inveja** não é boa, é **destrutiva**.

Quem diz sentir inveja, sente-se *reflexivo*, *compreensivo* ou até mesmo *divertido*. Quem **sente inveja**, sente `decepção`, `inconformismo`, `raiva`.

Decepção porque foi evidente que o `preconceito` atuou contra o seu favor. Raiva porque ninguém percebeu o quanto o tratamento diferenciado foi `injusto`. Decepção, porque você sabe que o seu trabalho foi excelente, mas outro foi escolhido porque sempre foi o `favorito`.

## A inveja é um instrumento ativista

<br>
Apesar de a inveja não ser um `valor`, ela é um `instrumento` social cuja finalidade é `forçar` alguma reflexão. A inveja é, muitas vezes, a `única` forma de evidenciar que existiu alguém que *talvez* merecesse mais atenção.

<br>

> Falem bem ou falem mal, mas falem de mim. <br>
> <cite> - Behdad Sami </cite>